In [5]:
import cv2
import numpy as np

In [6]:
#initiaze the camera
cap=cv2.VideoCapture(0)


In [3]:
#for face detection
face_cascade=cv2.CascadeClassifier("../cdMLAI/HaarCascade/haarcascade_frontalface_alt.xml")


In [4]:
##the running loop

skip=0
face_data=[]#to store the faces.to save memory save faces in grayscale
dataset_path='/Users/anuragsingh/Desktop/cdMLAI/Data/Face/'#path were faces are stored

file_name=input("Enter the name of the person : ")


while True:
    ret,frame=cap.read()#to read what is captured on the cam
    
    
    if ret==False:##like in any case if the camera does not open try it again
        continue
        
        
    faces=face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    #now if there are multiple faces then we need to sort the face in the order of there area.cause we only want to store the largest face
    faces=sorted(faces,key=lambda f:f[2]*f[3],reverse=True)
    
    
    for x,y,w,h in faces:#we iterate in reverse because the last face will be the largest one
        #x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        
        #Extract (Crop out the required face):Region of Interest
        offset=10#to give the extra region of a particular size in the image
        face_section=frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section=cv2.resize(face_section,(100,100))
        
        skip+=1
        if(skip%10==0):
            face_data.append(face_section)
            print(len(face_data))
            
            
            
        
    cv2.imshow("Frame",frame)
    cv2.imshow("Face_Section",face_section)
        
    
    
    
    ##part to exit the loop
    key_pressed=cv2.waitKey(1) & 0xFF
    if key_pressed==ord('q'):
        break
        
        
  

 ## now we convert aur face list array into a numpy array
face_data=np.asarray(face_data)
face_data=face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)



## now we save this data into system file
np.save(dataset_path+file_name+'.npy',face_data)
print("data successfully saved"+dataset_path+file_name+'.npy')


cap.release()
cv2.destroyAllWindows()
        

Enter the name of the person : satrudhan
[[293 243 407 407]]
[[305 250 385 385]]
[[293 254 394 394]]
[[332 263 358 358]]
[[330 258 370 370]]
[[324 244 389 389]]
[[331 252 385 385]]
[[325 251 393 393]]
[[323 248 397 397]]
[[332 276 361 361]]
1
[[324 271 373 373]]
[[322 269 385 385]]
[[328 280 370 370]]
[[348 302 322 322]]
[[333 283 362 362]]
[[349 286 355 355]]
[[328 284 376 376]]
[[321 282 382 382]]
[[311 276 394 394]]
[[317 290 373 373]]
2
[[315 285 372 372]]
[[321 283 373 373]]
[[313 273 388 388]]
[[309 274 393 393]]
[[315 278 382 382]]
[[306 273 393 393]]
[[301 275 401 401]]
()
[[330 303 335 335]]
[[319 290 372 372]]
[[323 292 358 358]]
3
[[320 285 371 371]]
[[324 289 362 362]]
()
[[316 281 378 378]]
[[322 291 361 361]]
[[299 272 398 398]]
[[305 280 389 389]]
[[313 292 372 372]]
[[287 280 394 394]]
[[309 290 373 373]]
()
[[304 282 380 380]]
4
[[303 281 378 378]]
[[296 286 382 382]]
[[281 287 394 394]]
[[279 296 378 378]]
[[276 295 380 380]]
[[274 301 372 372]]
[[292 299 372 372]]
[[

FileNotFoundError: [Errno 2] No such file or directory: '/Users/anuragsingh/Desktop/cdMLAI/Data/FaceDetection/satrudhan.npy'